apiVersion: apps/v1
kind: Deployment
metadata:
  name: x-tools-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: x-tools
  template:
    metadata:
      labels:
        app: x-tools
    spec:
      nodeSelector:
        kubernetes.io/hostname: pc1
      containers:
        - name: x-tools
          image: registry.cn-hangzhou.aliyuncs.com/ns-ykl/x-tools:v1
          command: ["/bin/sh", "-c", "while true; do echo Hello from x-tools; sleep 10; done"]
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: x-tools-svc-1
spec:
  selector:
    app: x-tools
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
#      nodePort: 30080
  type: ClusterIP
